export const BRAND_OPTIONS = [
  "Adidas",
  "Apple",
  "Bench",
  "Bershka",
  "Bayo",
  "Calvin Klein",
  "Charles & Keith",
  "Coach",
  "Converse",
  "Cotton On",
  "Crocs",
  "Decathlon",
  "Dior",
  "Fila",
  "Forever 21",
  "Guess",
  "H&M",
  "Havaianas",
  "Jordan",
  "Lacoste",
  "Levi's",
  "Louis Vuitton",
  "Mango",
  "Michael Kors",
  "Nike",
  "Oxygen",
  "Penshoppe",
  "Puma",
  "Shein",
  "Skechers",
  "SM Woman",
  "Sunnies Studios",
  "Uniqlo",
  "Vans",
  "World Balance",
  "Zara",
  "Zalora"
].sort((a, b) => a.localeCompare(b));